export const GET_PROPOSED_MATCH = 'GET_PROPOSED_MATCH'; 
export const APPROVE_PROPOSED_MATCH = 'APPROVE_PROPOSED_MATCH'; 
export const PROPOSE_MATCH   ='PROPOSE_MATCH'
export const GET_ALL_APPROVED_MATCHES = 'GET_ALL_APPROVED_MATCHES'
export const ALL_APPROVED_MATCHES = 'ALL_APPROVED_MATCHES'
export const GET_MY_APPROVED_MATCHES='GET_MY_APPROVED_MATCHES'
export const MY_APPROVED_MATCHES = 'MY_APPROVED_MATCHES'
export const UPDATE_RANKING = 'UPDATE_RANKING'
         
export const PROPOSED_MATCH_TO_CONFIRM = 'PROPOSED_MATCH_TO_CONFIRM'

