export const GET_MY_PROPOSED_TRAINING = 'GET_MY_PROPOSED_TRAINING'; 
export const MY_TRAININGS_TO_CONFIRM = 'MY_TRAININGS_TO_CONFIRM';
export const GET_MY_CONFIRMED_TRAINING = 'GET_MY_CONFIRMED_TRAINING'
export const MY_CONFIRMED_TRAINING = 'MY_CONFIRMED_TRAINING'